### PR TITLE
Mandate Absolute Path Fix #38

### LINKED ISSUE #38: Errors not appearing in UI
I'm getting errors in the VSCode Output of MyPy, but not in the UI.

Pylint and Flake8 errors are reflected properly.
```
Version: 1.60.0-insider
Commit: 44568e5947efa4811419e529e80fb14b7554cf61
Date: 2021-08-23T10:55:38.097Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 20.4.0
```

### PR DESCRIPTION
**Pull request by sidharthv96**

### CODE REVIEW

**Comment by sidharthv96** [comment]
Hi @matangover this fix would help out my team very much.

**Comment by matangover** [comment]
@sidharthv96 sorry for the delay :) I merged it and I'll make a release shortly

**Comment by sidharthv96** [comment]
Thanks for building and maintaining this amazing product! Helps us catch issues easily :)

**Comment by matangover** [comment]
You're welcome! I just published 0.2.1 with this fix

**Pull request closed without merging**
