### PR TITLE
Allow Mypy to be disabled for folders/projects in a monorepo

### PR DESCRIPTION
**Pull request by LaurensBosscher**
Hi,

First of all, thanks for this extension! Please consider this to be a draft implementation to take care of https://github.com/matangover/mypy-vscode/issues/41. 

I'm not sure if this is the best place to add this check but I'm happy to move this check if another place is more appropriate.

### CODE REVIEW

**Comment by LaurensBosscher** [comment]
@matangover Love your project, hope you had a good Christmas and New Years! Please let me know if you would like for me to change something on this PR.

**Comment by matangover** [comment]
Hey @LaurensBosscher thanks for the contribution! Looks good, I'm on vacation but I'll make a release when I get time after I get back

**Comment by LaurensBosscher** [comment]
@matangover , many thanks! Forget about the PR for now and enjoy your vacation. Looking forward to the new release after you get back!

**Comment by LaurensBosscher** [comment]
@matangover , hope you had a great holiday! Is there anything I can do to, to advance the next release? Thanks!

**Comment by matangover** [comment]
Hi, thank you! I hope to do it soon

**Comment by matangover** [comment]
I added some polishing touches to your contribution:
1. Fix mypy progress status bar icon being shown forever when mypy.enabled is false
2. Clear any existing mypy diagnostics when mypy is disabled

I'll release it tomorrow

**Pull request merged**
